include cmake/*.mk

all: make_sa4 make_sa3 make_sa2 sa_find3 sa_find2 make_sa1 find1 find2 find3 make_sa_find4
clean:
	rm -f *~ *.o utils/*.o utils/*~ a.out find1 find2 find3 make_sa1 make_sa2 make_sa3 make_sa4 sa_find2 sa_find3 make_sa_find4